[book]
title = "Алгоритмы и Структуры данных"
description = "Homework solutions for the Algorithms and Data Structures course at ITMO University"
authors = ["Nikita Panuhin"]
language = "ru"
src="."

[build]
build-dir = ".github/mdbook"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
additional-css = ['.github/assets/mdbook-admonish.css', '.github/assets/adjustments.css', '.github/assets/problem_toc.css']
additional-js = ['.github/assets/problem_toc.js']
no-section-label = true
git-repository-url = "https://github.com/npanuhin/ITMO-Algo"
edit-url-template = "https://github.com/npanuhin/ITMO-Algo/edit/master/{path}"
# input-404 = ""
cname = "algo.itmo.npanuhin.me"
mathjax-support = true

[output.html.search]
enable = false

[preprocessor.mathjax]
command = "python mathjax.py"

[preprocessor.problem_toc]
command = "python problem_toc.py"

[preprocessor.admonish]
command = "mdbook-admonish"
