[book]
title = "Алгоритмы и Структуры данных"
description = "Homework solutions for the Algorithms and Data Structures course at ITMO University"
authors = ["Nikita Panuhin"]
language = "ru"
src="."

[build]
build-dir = ".github/mdbook"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
additional-css = [
	'.github/assets/adjustments.css',
	'.github/assets/problem_toc.css',
	'.github/assets/katex/katex.min.css'
]
additional-js = [
	'.github/assets/problem_toc.js',
	'.github/assets/katex/katex.min.js',
	'.github/assets/katex/contrib/auto-render.min.js',
	'.github/assets/katex_fix.js'
]
no-section-label = true
git-repository-url = "https://github.com/npanuhin/ITMO-Algo"
# edit-url-template = "https://github.com/npanuhin/ITMO-Algo/edit/master/{path}"
# input-404 = ""
cname = "algo.itmo.npanuhin.me"

[output.html.search]
enable = false

[output.html.print]
enable = false

[preprocessor.problem_toc]
command = "python .github/problem_toc.py"
